baseurl: https://byrondonaldson.github.io/
languageCode: en-us
title: Byron Donaldson
theme: "hugo-ivy"
googleAnalytics: "G-7FLW863FJB"
disqusShortname: "bongi"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "About"
      url: "/about"
      weight: 1
    - name: "Links"
      url: "/links/"
      weight: 2
    - name: "Papers"
      url: "/papers/"
      weight: 3
    - name: "Writing"
      url: "/writing/"
      weight: 4


params:
  description: ""
  footer: "&copy; [Byron Donaldson](https://byrondonaldson.github.io) 2022"
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"
  highlightjsVersion: "9.12.0"
  twitterimage: "/images/logo.png"
  
  logo:
    alt: Logo
    height: 60
    url: logo.png
    width: 60

markup:
  goldmark:
    renderer:
      unsafe: true
